### ISSUE TITLE
CacheMono - onCacheMissResume is being called even if there is a value in the cache

### ISSUE THREAD

**Issue by hmble2** [reactor/reactor-addons#234] opened 2020-05-28 16:46 UTC
Even if the value is present in the cache, onCacheMissResume is fired every time.
Issue is due to `otherSupplier.get()` in method argument is not deferred and hence called immediately.

```
	public static <KEY, VALUE> MonoCacheBuilderCacheMiss<KEY, VALUE> lookup(
			Function<KEY, Mono<Signal<? extends VALUE>>> reader, KEY key) {
		return otherSupplier -> writer -> Mono.defer(() ->
				reader.apply(key)
				  .switchIfEmpty(otherSupplier.get()
				                              .materialize()
				                              .flatMap(signal -> writer.apply(key, signal)
				                                                       .then(Mono.just(signal))
				                              )
				  )
				  .dematerialize());
	}
```
and at,

```
public static <KEY, VALUE> MonoCacheBuilderMapMiss<VALUE> lookup(Map<KEY, ? super Signal<? extends VALUE>> cacheMap, KEY key) {
    return otherSupplier -> Mono.defer(() ->
            Mono.justOrEmpty(cacheMap.get(key))
                .switchIfEmpty(otherSupplier.get().materialize()
                                .doOnNext(value -> cacheMap.put(key, value)))
                .dematerialize()
    );
}
```
This can be fixed by adding Mono.defer to otherSupplier.get in all places having onCacheMissResume callback  e.g.

	public static <KEY, VALUE> MonoCacheBuilderCacheMiss<KEY, VALUE> lookup(
			Function<KEY, Mono<Signal<? extends VALUE>>> reader, KEY key) {
		return otherSupplier -> writer -> Mono.defer(() ->
				reader.apply(key)
				  .switchIfEmpty(Mono.defer(()->otherSupplier.get()
				                              .materialize()
				                              .flatMap(signal -> writer.apply(key, signal)
				                                                       .then(Mono.just(signal))
				                              ))
				  )
				  .dematerialize());
	}

Workaround: Until the issue is fixed, callback can add a defer to resolve the issue:
`                .onCacheMissResume(() -> Mono.defer(() -> createExpensiveGraph(key)))`

**Comment by lawulu** [comment] 2020-07-09 05:07
I have the same issue. But I don't think it's duo to `CacheMono`.
You can put value in the cache at the beginning to check if onCacheMissResume is fired.

I adapted the unit test from the official repo to verify this:
`    AtomicInteger sourceSubscribed = new AtomicInteger();
    Mono<Integer> source = Mono.fromCallable(()->{
      System.out.println("here");
      return 123;
    }).doOnSubscribe(sub -> sourceSubscribed.incrementAndGet());
    AtomicReference<Context> storeRef = new AtomicReference<>(Context.empty());
   
     String key = "burger";
    storeRef.updateAndGet(ctx -> ctx.put(key,321)); //put the value firstly

    Mono<Integer> cachedMono = CacheMono
        .lookup(k -> Mono.justOrEmpty(storeRef.get().<Integer>getOrEmpty(k))
                .map(Signal::next),
            key)
        .onCacheMissResume(source)
        .andWriteWith((k, sig) -> Mono.fromRunnable(() ->
            storeRef.updateAndGet(ctx -> ctx.put(k, sig.get())))
        );

    cachedMono.subscribe(System.out::println);
    System.out.println(sourceSubscribed.get());
` 
you can see that there is no `here` output in the console.

So, I think the reason is there is no lock/synchronization when the cache is missed. 
For example: 
There is no value in the cache at the beginning.
Request 1,2,3 comes to get the value from cache at the same time,
Request 1 gets null and fires the `onCacheMissResume` 
When Request 2 comes, the write operation fired by Request 1 haven't finished, so it will fire the write again due to the null.
When Request 3 comes, it will get the proper value if the write operation have finished.

**Comment by winster** [comment] 2020-09-10 14:05
I was also thinking this as an issue till I see this discussion https://stackoverflow.com/questions/63812343/spring-webflux-with-in-memory-cache

**Comment by hmble2** [comment] 2020-09-14 16:05
The confusion is caused due to mixing of imperative and reactive style. However, should the Mono that gets invoked (i.e. fetchValueFromSource) when onCacheMissResume is fired needed to be wired at assembly time? Adding a Mono.defer could eliminate the confusion and thus won't execute any imperative code in method Mono getValueFromSource(). Please see here https://stackoverflow.com/questions/54974326/how-to-make-reactor-cache-cachemono-not-to-call-calculation-twice @simonbasle @alex-pumpkin

**Comment by simonbasle** [comment] 2020-09-14 16:14
is it the same as / fixed by https://github.com/reactor/reactor-addons/pull/227 by any chance ? (that PR has just been released in 3.3.4.RELEASE and 3.4.0-RC1)

**Comment by hmble2** [comment] 2020-09-14 18:15
@simonbasle yeah, exact same issue. Thanks, this should be okay to close.

**Comment by simonbasle** [comment] 2020-09-15 07:59
Duplicate of #227

**Closed by simonbasle** 2020-09-15 07:59 UTC
Labels: :question:need-triage
